FIND_LIBRARY(GLEW_LIBRARIES
             NAMES GLEW glew32)

FIND_PATH(GLEW_INCLUDES
          NAMES glew.h
          PATH_SUFFIXES GL)

IF(GLEW_INCLUDES AND GLEW_LIBRARIES)

    SET(GLEW_FOUND TRUE)

    IF(VERBOSE)
        MESSAGE(STATUS "GLEW includes = ${GLEW_INCLUDES}")
        MESSAGE(STATUS "GLEW library = ${GLEW_LIBRARIES}")
    ENDIF()

ELSE()

    MESSAGE(STATUS "GLEW not found")

ENDIF()
